# Generated by Django 4.2.1 on 2023-05-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=30, verbose_name='Usuário')),
                ('lider', models.CharField(max_length=50)),
                ('chamado', models.IntegerField(max_length=8)),
            ],
        ),
    ]
