# Generated by Django 4.2.1 on 2023-05-30 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='chamado',
        ),
    ]
