# Generated by Django 4.2.1 on 2023-05-31 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_employee_cargo_employee_departamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='lider',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
