# Generated by Django 4.2.1 on 2023-05-31 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_alter_employee_lider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='lider',
            field=models.CharField(blank=True, default='Não definido', max_length=50, null=True),
        ),
    ]
