# Generated by Django 4.2.1 on 2023-06-07 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_alter_employee_cargo_alter_employee_departamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='lider_email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
    ]
